[package]
name = "skidscan-macros"
version = "0.1.0"
authors = ["William Venner <william@venner.io>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = "1.0"

[features]
obfuscate = []
